name: "Continuous Delivery"

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Microservice - Continuous Integration / Build"]
    branches: ["main"]
    types:
      - completed

permissions:
  contents: read
  pull-requests: write

env:
  AWS_REGION_DEFAULT: us-east-1
  AWS_ECR_REPOSITORY: tech-challenge-lanchonete/orders-vitorrafael
  AWS_ECR_REGISTRY: 045628470274.dkr.ecr.us-east-1.amazonaws.com
  EKS_CLUSTER_NAME: tech-challenge-lanchonete
  K8S_DEPLOYMENT_NAME: orders

jobs:
  tag:
    if: ${{ github.event_name == 'workflow_dispatch' || github.event.workflow_run.conclusion == 'success' }}
    name: "Bump version and push tag"
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Bump Version and Push Tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

    outputs:
      new_tag: ${{ steps.tag_version.outputs.new_tag }}

  docker-build-and-push:
    name: "Docker - Build & Push to ECR"
    needs: tag
    runs-on: ubuntu-latest
    env:
      TAG: ${{ needs.tag.outputs.new_tag }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ env.AWS_REGION_DEFAULT }}

      - name: Login To Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build Image Name
        id: build-image-name
        run: |
          echo "IMAGE_NAME=${{ env.AWS_ECR_REGISTRY }}/${{ env.AWS_ECR_REPOSITORY }}:${{ env.TAG }}" >> "$GITHUB_OUTPUT"

      - name: Build & Tag Image
        env:
          IMAGE_NAME: ${{ steps.build-image-name.outputs.IMAGE_NAME }}
        run: |
          docker build -t $IMAGE_NAME .

      - name: Push Image
        if: github.ref == 'refs/heads/main'
        env:
          IMAGE_NAME: ${{ steps.build-image-name.outputs.IMAGE_NAME }}
        run: |
          docker push $IMAGE_NAME

    outputs:
      IMAGE_NAME: ${{ steps.build-image-name.outputs.IMAGE_NAME }}

  rollout-update:
    name: "Rollout Update"
    runs-on: ubuntu-latest
    needs: docker-build-and-push
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ env.AWS_REGION_DEFAULT }}

      - name: Connect to AWS EKS Cluster
        if: github.ref == 'refs/heads/main'
        run: aws eks update-kubeconfig --name ${{ env.EKS_CLUSTER_NAME }} --region ${{ env.AWS_REGION_DEFAULT }}

      - name: Rollout Update to Kubernetes Deployment
        if: github.ref == 'refs/heads/main'
        env:
          NEW_IMAGE_NAME: ${{ needs.docker-build-and-push.outputs.IMAGE_NAME }}
        run: kubectl set image deployments/$K8S_DEPLOYMENT_NAME $K8S_DEPLOYMENT_NAME=$NEW_IMAGE_NAME
